### PR TITLE
add template function to parse different types of values into an integer

### PR DESCRIPTION
**Pull request by tlayh**
parseInt templatefunction to convert different numeric types and strings into integer.

### CODE REVIEW

**Comment by tlayh** [comment]
I would like to convert math.bigFloat to integer also, but I did not find a good looking solution for that.

**Comment by dylan-provost** [comment]
Might be misleading with the branch name, but thought it would be a good idea to add a parseFloat here, as both functions have a similar pattern and run similar tests

**Comment by bastianccm** [comment]
@tlayh you can do
```
var num big.Float
// ...
fnum, _ := num.Float64()
return pugjs.Number(fnum)
```

**Comment by tlayh** [comment]
> @tlayh you can do
> 
> ```
> var num big.Float
> // ...
> fnum, _ := num.Float64()
> return pugjs.Number(fnum)
> ```

Dylan already implemented it.

**Pull request merged**
